### PR TITLE
Correctly retrieve type when declared directly

### LINKED ISSUE #87: object notation should be optional
hi,

when i'm trying to generate a type and a mutation from this example schema, the generator will crashes because of missing 'type' property on the field.

```js
'use strict'

var mongoose = require('mongoose')
var example= new mongoose.Schema({
	title: String
})

module.exports = mongoose.model('Example', example)
```

changing the schema in this way make the generator works again:

```js
'use strict'

var mongoose = require('mongoose')
var example= new mongoose.Schema({
	title: { type: String, }
})

module.exports = mongoose.model('Example', example)
```

### PR DESCRIPTION
**Pull request by JCMais**
You can declare the type of mongoose fields directly, without using an object, like `{ field: String }` or `{ field: Schema.Types.ObjectId }`.

Fixes #87 

https://runkit.com/jcmais/5900b3565581b700125e1ab5

### CODE REVIEW

**Comment by lucasbento** [comment]
Nice!

**Comment by lucasbento** [comment]
@JCMais: would you mind adding a test for this?

File: packages/generator/src/utils.js [hunk 1]
```diff
@@ -135,19 +135,25 @@ const getSchemaFieldsFromAst = (node, withTimestamps) => {
...
+
   astSchemaFields.forEach((field) => {
     const name = field.key.name;
 
     const fieldDefinition = {};
 
     if (field.value.type === 'ArrayExpression') {
       return;
+    } else if (validSingleValueTypes.indexOf(field.value.type) !== -1) {
+      fieldDefinition['type'] = field.value.property ? field.value.property.name : field.value.name;
```
Comment (JCMais) [inline packages/generator/src/utils.js]: Will fix.

File: packages/generator/fixtures/User.js [hunk 2]
```diff
@@ -19,6 +19,7 @@ const Schema = new mongoose.Schema({
     type: Boolean,
     default: true,
   },
+  lastLoginAt: Date,
```
Comment (lucasbento) [inline packages/generator/fixtures/User.js]: 💅
